/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope;

// Take over all clients immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Initialize Firebase Push Notifications safely
self.addEventListener('activate', () => {
  if (typeof indexedDB === 'undefined') {
    console.warn('[SW] IndexedDB unavailable – skipping Firebase Messaging init.');
    return;
  }

  try {
    const firebaseConfig = {
      apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
      authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: import.meta.env.VITE_FIREBASE_APP_ID,
    };

    if (firebaseConfig.apiKey) {
      const app = initializeApp(firebaseConfig);
      const messaging = getMessaging(app);

      onBackgroundMessage(messaging, (payload) => {
        console.log('[SW] Received background message', payload);
        const notificationTitle = payload.notification?.title ?? 'Mysuru Paakashale';
        const notificationOptions = {
          body: payload.notification?.body,
          icon: '/favicon.svg',
        };
        self.registration.showNotification(notificationTitle, notificationOptions);
      });
    }
  } catch (error) {
    console.error('[SW] Firebase Messaging init failed:', error);
  }
});

