/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { initializeApp } from 'firebase/app';
import { getMessaging, onBackgroundMessage } from 'firebase/messaging/sw';

declare let self: ServiceWorkerGlobalScope;

// Take over all clients immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell Navigation Fallback
// This ensures that when a user refreshes the page or navigates directly
// to a client-side route, the service worker immediately serves the precached
// index.html shell instead of going to the network.
try {
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler);
  registerRoute(navigationRoute);
} catch (error) {
  console.warn('[SW] NavigationRoute registration failed', error);
}

// Initialize Firebase Push Notifications safely
// This must be done synchronously at the top level of the service worker,
// NOT inside an 'activate' listener, so the 'push' event handler is registered immediately.
if (typeof indexedDB !== 'undefined') {
  try {
    const firebaseConfig = {
      apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
      authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
      storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: import.meta.env.VITE_FIREBASE_APP_ID,
    };

    if (firebaseConfig.apiKey) {
      const app = initializeApp(firebaseConfig);
      const messaging = getMessaging(app);

      onBackgroundMessage(messaging, (payload) => {
        console.log('[SW] Received background message', payload);
        const notificationTitle = payload.notification?.title ?? 'Mysuru Paakashale';
        const notificationOptions = {
          body: payload.notification?.body,
          icon: '/favicon.svg',
        };
        self.registration.showNotification(notificationTitle, notificationOptions);
      });
    }
  } catch (error) {
    console.error('[SW] Firebase Messaging init failed:', error);
  }
} else {
  console.warn('[SW] IndexedDB unavailable – skipping Firebase Messaging init.');
}

