/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Take over all clients immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Initialize Firebase Push Notifications after activation.
// Deferred to the 'activate' event so that any Firebase SDK errors (e.g. from
// restricted IndexedDB on older Android) are isolated and cannot cause the
// navigator.serviceWorker.register() promise to reject, which would surface
// as an unhandled rejection in Sentry.
self.addEventListener('activate', () => {
  // Firebase Messaging requires IndexedDB internally. Guard against restricted
  // environments (e.g. Android 10 / Chrome Mobile with storage partitioning).
  if (typeof indexedDB === 'undefined') {
    console.warn('[SW] IndexedDB unavailable – skipping Firebase Messaging init.');
    return;
  }

  // Dynamic import keeps Firebase out of the synchronous evaluation path,
  // so a module-level error cannot abort SW registration.
  import('firebase/app').then(({ initializeApp }) => {
    return import('firebase/messaging/sw').then(({ getMessaging, onBackgroundMessage }) => {
      try {
        const firebaseConfig = {
          apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
          authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
          projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
          storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
          messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
          appId: import.meta.env.VITE_FIREBASE_APP_ID,
        };

        const app = initializeApp(firebaseConfig);
        const messaging = getMessaging(app);

        onBackgroundMessage(messaging, (payload) => {
          console.log('[SW] Received background message', payload);
          const notificationTitle = payload.notification?.title ?? 'Mysuru Paakashale';
          const notificationOptions = {
            body: payload.notification?.body,
            icon: '/favicon.svg',
          };
          self.registration.showNotification(notificationTitle, notificationOptions);
        });
      } catch (error) {
        console.error('[SW] Firebase Messaging init failed:', error);
      }
    });
  }).catch((error) => {
    console.error('[SW] Failed to load Firebase modules:', error);
  });
});

